### ISSUE TITLE
How does one use pipes 

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [forflo/shepi#2]
As we all know Lua does not have `|` operator which makes me wonder how does one uses this feature. 
Even tests don't pass:
```
~/Projects/shepi master
❯ busted -lpath "./source/?.lua" --pattern "spec" tests/
✱
0 successes / 0 failures / 1 error / 0 pending : 0.000015 seconds

Error → tests/spec_smoketest.lua:21: unexpected symbol near '|'
tests/spec_smoketest.lua
```

**Comment by forflo** [comment]
> As we all know Lua does not have | operator

Lua does have the binary or operator.

https://www.lua.org/manual/5.3/manual.html#3.4.2

**Comment by forflo** [comment]
I am closing this for now.
